[project]
name = "cv-robotics-onedge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.8",
    "opencv-python>=4.13.0.92",
    "tqdm>=4.67.3",
    "ultralytics>=8.4.14",
]
